name: KiCad PR Diff

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  discover-projects:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.collect.outputs.projects }}
    steps:
      - uses: actions/checkout@v4

      - name: Find KiCad projects
        id: collect
        run: |
          FILES=$(find electronics -name "*.kicad_pro")
          JSON=$(printf '%s\n' $FILES | jq -R -s 'split("\n") | map(select(length>0))' -c)
          echo "projects=$JSON" >> $GITHUB_OUTPUT

  kiri-diff:
    needs: discover-projects
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: ${{ fromJson(needs.discover-projects.outputs.projects) }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run Kiri Diff (using leoheck/kiri)
        run: |
          PROJECT="${{ matrix.project }}"
          PROJECT_DIR=$(dirname "$PROJECT")

          echo "Running Kiri for: $PROJECT"
         
          docker run --rm \
            -v "$PWD":/project \
            leoheck/kiri:latest \
            kiri -p /project/${PROJECT}


      # - name: Upload Kiri output
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: kiri-output-${{ matrix.project }}
      #     path: ${{ matrix.project }}/../.kiri
      #     if-no-files-found: warn
